projects:
  planted:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
        graphQLApiId: ehvuy77fd5c6fh3rs57k2tbsjm
      endpoints:
        prod: >-
          https://5wbptssaafe3riny5ojish5lq4.appsync-api.eu-west-1.amazonaws.com/graphql
