projects:
  planted:
    schemaPath: src\graphql\schema.json
    includes:
      - src\data\graphql\**\*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: API.js
        docsFilePath: src\data\graphql
        graphQLApiId: a2cqee6zq5gona2qqtqrt6dmku
      endpoints:
        prod: >-
          https://x57v4dsu5fgplmw553iocewdtu.appsync-api.eu-west-1.amazonaws.com/graphql
