// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://x57v4dsu5fgplmw553iocewdtu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sroqbl3sg5c67mipv43rn5fevi",
    "aws_cognito_identity_pool_id": "eu-west-1:e063563b-6e53-443f-af70-958ce3ef2e50",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_EIOUiOfVx",
    "aws_user_pools_web_client_id": "61c0sn8ep4jj6rgu9u934ofab"
};


export default awsmobile;
